version: '3'

services:
  web:
    build: .
    ports:
      - "8081:8081"
    command: /bin/bash
    tty: true
    stdin_open: true
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: albums

volumes:
  postgres_data:
